# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: booking-service
  description: A service for handling travel bookings, part of the Amadeus travel platform.
  labels:
    team: reservations
    domain: travel-technology
    project: amadeus-platform
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: reservations-team
  system: booking-system
  providesApis:
    - api:booking-api
  dependsOn:
    - api:payment-gateway-api
    - api:inventory-management-api
  subcomponents:
    - component: user-notifications
    - component: booking-validation
  links:
    - url: https://booking.amadeus.com
      title: "Booking Service - Production"
    - url: https://staging.booking.amadeus.com
      title: "Booking Service - Staging"
    - url: https://github.com/amadeus-tech/booking-service
      title: "GitHub Repository"
    - url: https://jira.amadeus.com/projects/BOOK
      title: "JIRA Project"
    - url: https://docs.amadeus.com/booking-service
      title: "Service Documentation"
    - url: https://grafana.amadeus.com/d/abc123/booking-service
      title: "Grafana Dashboard"
