# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: booking-service
  description: A service for handling travel bookings, part of the Amadeus travel platform.
  labels:
    team: reservations
    project: urgent
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: amadeus4dev/amadeus-node
spec:
  type: service
  lifecycle: production
  owner: reservations-team
  system: booking
  providesApis:
    - booking-api
  dependsOn:
    - api:payment-gateway-api
    - api:inventory-management-api
  subcomponents:
    - component: user-notifications
    - component: booking-validation
  links:
    links:
    - url: https://amadeus.wd3.myworkdayjobs.com/en-US/jobs/jobs/details/Product-Manager-Cloud-Transformation_R23448?locationCountry=54c5b6971ffb4bf0b116fe7651ec789a&Worker_Type=500e98adb60a01e732dd99deee1acf1d
      title: "Internships"
